apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: node-app
  namespace: default

spec:
  maxReplicas: 9
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app
  targetCPUUtilizationPercentage: 50